# Generated by Django 3.0.6 on 2020-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCargo', models.IntegerField()),
                ('categoriaCargo', models.CharField(max_length=50)),
                ('salarioCargo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDepart', models.IntegerField()),
                ('nomeDepart', models.CharField(max_length=50)),
                ('localDepart', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_nascimento',
            new_name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
